### ISSUE TITLE
Disconnect While AFK for a while

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/BabyWars#36]
# 因离开而掉线
## 情况

在游戏标题界面及游戏过程中，如果一段时间内玩家未进行任何操作则会掉线。这种情况在玩家之后操作时提示“与服务器的连接被断开...正在重新尝试连接”时被发觉。
## 影响

在游戏标题界面的情况下，超时掉线是有益的。因为他能减轻服务器的带宽压力；而在游戏中超时掉线则并不是什么好事情。一个玩家很可能在因为观看对手操作的时候因为符合上述条件而掉线。如果没有外界的交流，他在一段时间内难以判断是自己掉线还是对手正在思考。如果是对手思考，尝试刷新战局的玩家会造成多余的服务器请求，这在未来玩家数目较多时会造成更多的服务器压力；而如果确实掉线，则由于没有第一时间进行操作，浪费了玩家和对手的时间，在频繁出现的情况下游戏体验则将会下降。
## 解决建议

我没有通读代码，暂无解决建议。

**Comment by Babygogogo** [comment]
RushFTK你好！目前服务器并不会主动切断连接，所以你描述的情况可能是网络不稳定、或是代码中的bug造成的。请问从不操作到断线，大概有多长时间？另外，是不是每次一到这个时间就必然会断线？

**Comment by RushFTK** [comment]
Babygogogo你好！
详细的时间没有进行过测算，不过是在有线链接的情况下，在大约10分钟后**必发性**的问题，因此才来上报。
希望我的情况描述能有所帮助。

**Comment by Babygogogo** [comment]
这有可能是bug，我将尽快修复。谢谢反馈！

**Comment by Babygogogo** [comment]
目前尝试通过心跳包（20秒一次）的方式来维持连接并检测是否断连，理论上应该可以缓解这个问题。该更新将于本周五实装，届时视乎效果再决定是否关闭本issue。

经过一次fix，心跳包貌似可以工作了。

**Comment by RushFTK** [comment]
在标题界面断线后仍不会自动重连，因而reopen。

**Comment by Babygogogo** [comment]
正在修改相关代码，实际效果还是要等到周五实装后才能知道了。

**Comment by Babygogogo** [comment]
目前似乎没有发现与心跳包直接相关的bug，所以关闭本issue。
