### ISSUE TITLE
希望改善服务器

### ISSUE THREAD

**Issue by LlMT13496** [Babygogogo/BabyWars#38]
我用移动运营商的WiFi一直连接不上服务器，用流量才行，但是我没有流量……希望能改善这个问题

**Comment by Babygogogo** [comment]
LIMT13496你好！
目前我使用的是免费的服务器解析软件，你所说的连接不上的问题有可能是因此产生的。等到游戏完善以后，我会使用付费的软件，希望到时能够解决这个问题，但目前的确没有解决的办法，抱歉！
P.S. 游戏有pc版，如果你有条件可以尝试一下，说不定能解决问题。
