### ISSUE TITLE
阿飞的建议

### ISSUE THREAD

**Issue by blackwave** [Babygogogo/BabyWars#41]
日常
攻击:-30~+30
防御:-30~+30
最大幸运:0~+30
最小幸运:-30~+10
最大幸运必须大于最小幸运，而且幸运不能叠加，只能改变成某个值
移动:-1~+1
射程:-2~+2
占领:-30~+50
占领改变值不能叠加，只能改成为某个值
修复值:-2~+7
修复价格:-50~+100
造价:-20~+50
造价改变值不能叠加，只能改变成某个值
Cop
攻击:-50~+300
防御:-50~+300
最大幸运:0~100
最小幸运:-100~+40
移动:-2~+2
射程:-2~+2
占领:0~+2000
造价:-50~+0
己方hp:-9~+9
对方hp:-5~+9

**Comment by RushFTK** [comment]
合并：#59 :建议恢复50%造价梯度。

**Comment by Babygogogo** [comment]
因长期无人回复，故关闭本issue。另，一个issue应尽量集中于单个技能或话题，以方便阅读和复查。
