### ISSUE TITLE
主动技能的效果叠加与默认加成问题

### ISSUE THREAD

**Issue by 3Au** [Babygogogo/BabyWars#44]
综合考虑AW的CO能力构成及后期平衡，并加强主动技与日常关联性，简易主动技的加成做如下调整：
（1）主动技自带10攻防加成
这个仁者见仁了吧，不过自带默认加成不论是哪一个原作（除了AW2的攻击）都是存在的
（2）主动技发动时留有日常效果，主动技的加成在日常基础上
1）释义：比如日常+20攻，那么主动技+10，就是在主动技发动状态下+30。如果算上第（1）条自带那就是+40。
2）评判主动技的效果永远是基于日常的。这么做的好处是方便后期规划。同时也与原作部分优点吻合

**Comment by Babygogogo** [comment]
客套话我就不多说了哈，关于这三点：
1.  实现默认的+10/+10在程序是可以做到的。目前没有默认加攻防，主要是考虑有默认加成的话，可能会干扰玩家阅读技能信息，以及干扰技能平衡设计。如果大家普遍认为有必要默认加攻防，那么我会相应修改。
2. 目前的主动技效果是建立在日常技能的基础上的。
3. 这一条的意思是说，评判一个主动技效果的强弱，需要考虑日常技的配置吗？也就是说，同一个主动技效果，在搭配不同的日常技时，需要有不同的技能点消耗？

**Comment by 3Au** [comment]
第二条第三条请无视吧=、=

**Comment by RushFTK** [comment]
> 主动技自带10攻防加成

现在COP槽最少可以允许长度为1，而且不同技能复合后本身可以配置出槽子很长，很强力的能力。因此感觉自带+10/+10难以控制COP连发的导致的优势。

**Comment by Babygogogo** [comment]
本issue相关的话题最近已基本无人提出新的建议，故关闭。
