### ISSUE TITLE
Remove some maps due to low quality 

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/BabyWars#45]
回合制游戏中地图质量与游戏体验直接挂钩。
经过一段时间的观察，以下地图我认为质量较低，不适于这款游戏，并且也已经无人问津，建议移除：
![default](https://cloud.githubusercontent.com/assets/20500319/18076967/b78562aa-6eb4-11e6-8410-8bc0d545688f.png)
插座山脉 作者：babygogogo：
理由：1. **严重的先手优势问题**：先手可以在第一时间抢先占领一座城市，并且后手在尝试占领时会遭到先手骚扰，导致先手一直有1k的经济优势，在低收入的地图上这收入会使得优势进一步增大。
2. **长时间未更新**：这张地图已经很长时间没有更新过，并且地图仍然拥有关键问题。

![default](https://cloud.githubusercontent.com/assets/20500319/18077006/f5506954-6eb4-11e6-85bc-6aae9f36e8e0.png)
彗星的脉动：作者：RushFTK 搬运：电玩小子
1. **冗长的地形** ： 地图本身完成度不高，过多的阻挡物与过大的地图导致玩家需要很长时间才能交火，游戏时间较长，这会降低游戏体验。
2. **长时间未更新**：这张地图已经很长时间没有更新过，并且地图仍然拥有关键问题。

![default](https://cloud.githubusercontent.com/assets/20500319/18077068/65cae894-6eb5-11e6-9b08-85a7260d09fe.png)
一团糟：作者RushFTK
1. **严重的先手优势问题**：任何一方首先控制中心地区的玩家可以利用控制对方机场与航母，由于阻挡物的原因远程不可清除，这使得地图的战略性大大降低。
2. **作者已经放弃这张地图的更新**

综上，我认为在BabyWars中移除这三幅地图对提升游戏体验具有好处。

**Comment by Babygogogo** [comment]
关于地图问题，我倾向于不针对某一张图，而是针对整个地图管理机制来进行讨论。
我个人有个初步的想法，将地图至少分为三类：
- 高水平地图：平衡性和可玩性没有什么毛病，可以直接用于竞技
- 中等水平地图：有少量问题，经过作者的改进有望成为高水平地图
- 其他地图：有明显的问题；或尚未经过审议

作图不是简单的事情，任何人都需要时间去磨练技术。我个人比较希望BabyWars能够成为作图新人们可以锻炼技术的平台，但这需要审核地图的人付出努力，所以我不能也不会强求。上面写的分类方法也只是初步的想法，欢迎各位讨论，谢谢：）

最后，具体到这三张图，该砍就砍，我没有任何反对意见：）

**Comment by RushFTK** [comment]
关于该三张图的淘汰，还需要其他参与人员商量。（不过如果一段时间没人发表意见我就执行了）
另外，该问题串尚未涉及到地图分类问题，分类的设计应该从玩家数，地图水平等进行讨论，这里我认为可以直接使用AWBW中的地图分类系统即可，详细的想法有时间我会单开issue讨论串，谢谢你这么上心提供意见 ：）

**Comment by RushFTK** [comment]
The process was done while #53 Merged.
