### ISSUE TITLE
来自 战队脸黑非洲人之酋长兵敢死队 的建议

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/BabyWars#47]
原文： 

现在内部结构只是除了技能有点问题基本没什么大问题，技能上下限降低改成5%(比如:40.35.30....)，日常和P槽去掉技能4，SP留下技能4，日常移动最好去掉或改成+1-1，只是要比原作好些点就行，因为过头反而可能扯自己后腿所以适中就好(表达简略明白，让新人一看就懂),暂时就解决了技暂系统看上去过于复杂(一刀直接砍死一切)！页面也能简化还能加入一些新功能(以燃战的页面为参考模样，比如，创局和参战地图放在一起，查看自建地图或他方创建的地图)，页面如何分布到时候要做时，我会说明的，因为里面空间还很多浪费不得，即可简单化也能充分利用空间！致于形式表达我觉得可以留到比较后期也行，例如:aw3的鸟，dor剧情到某关时(被追杀到天涯海角那关)后面的夕阳也可利用起来(如果到时需要新图块大不了我来画)生机勃勃视觉效果最好了，让新人第一次玩印象分也可以高一些，天气系统也必不可少，天气留到最后说是因为基本没人用！现在这样策划我估计最好的前进方向。意下如何？

![pic20160830165954](https://cloud.githubusercontent.com/assets/20500319/18082862/43ef575a-6ed3-11e6-828a-0c236fefe552.png)

**Comment by Babygogogo** [comment]
这个issue涉及的内容比较多，我已建议andy下次分开说。那么现在简单回复如下：
1. 关于技能系统的简化：这条建议与#42 比较类似，请参考。
2. 关于界面设计：只用言语描述不太好理解，如果方便请画个草图什么的吧。
3. 关于画面：目前并没有专职美工，所以暂时可能无法做出很漂亮的画面，请见谅。
4. 关于天气系统：天气系统依赖于雾战系统，而雾战系统尚未完成，所以天气系统也暂时无法开工，请见谅。

**Comment by Babygogogo** [comment]
因长期无人回复，所以关闭本issue。日后如需讨论相关问题，新建issue即可。
