### ISSUE TITLE
赵天同对日常幸运的分析

### ISSUE THREAD

**Issue by zhaotiantong** [Babygogogo/BabyWars#50]
日常幸运现在1级80点，我认为比较平衡

首先不考虑其它因素，单纯分析不同地形的内战伤害。相同单位内战草地50-60，城46-56，林42-52。分别对比400点的攻击和幸运，40级攻击是70-80，64-74，59-69，5级幸运是50-85，46-81，42-75。平均起来攻击是75，69，64，幸运是68，64，59，加幸运肯定要亏一些……而且星越少，幸运越亏，即使四星，幸运也不赚

然后考虑兵种
对于强兵打弱兵，比如坦克打兵，加幸运会更亏，只有弱兵打强兵时，加幸运才会赚，比如兵打坦克。但幸运还是不亏，因为一次弱兵打强兵赚回来的钱，足够抵消内战和强打弱的劣势，比如一个兵打爆对方一个坦克，可以抵消三次坦克内战的劣势
所以说幸运方应该尽量避免同兵种内战，而普通方应该尽量进行内战

接下来考虑初始技能点数
结论是，100初始点数时，幸运稍弱，500初始点数时，幸运极强，原因有三：
1.如果对方加防，那幸运很强；如果对方减防，那幸运就弱。初始点数越多，对方加防的可能性就越大，幸运就越强
2.幸运和其它正常技能（攻防金钱）相比，有一个最大的优势，就是上限高。攻防最高500，金钱最高750，而幸运1600。在初始点数少的时候，点数本身很关键，很多日常配法都不会把4个格子占满，而幸运也很难达到上限，发挥不出最大威力；但在初始点数多的时候，4个格子基本都是满的，同样一个格子，攻击只能用掉500点，而幸运可以加1600，因此会强一些
3.幸运要比攻击强，必须要有一定量的积累。5级幸运可以比40级攻击强，但1级幸运一定比8级攻击弱。因为即使给了你+5%幸运，你还是没法拿兵打坦克。既亏钱，又给人家坦克送等级。想要兵打坦克，幸运至少要加到4级，而这已经需要320点了。这个游戏凑负点数是很痛苦的，攻防还好，像资金这种，正点数值750的50级，负点数只给600

最后说一下什么地形适合选幸运
首先幸运最强的就是原本数值打对方不到一格的进攻，所以纯海空战和纯远程互打都是劣势。而在小图或厂房比很大的图中，幸运很难克制对方的步兵炮兵海。但在厂房比较小的图或大图上，能够轻易出wartank和攻击机，幸运就很强了。因为对方的wartank要防你的所有兵种，而你的wartank只需要防对手的大件；攻击机也是，相互牵制，但你的攻击机对地输出比对手高得多。至于海陆同时打的图，我不太熟，暂不评论

**Comment by RushFTK** [comment]
引用： **3.幸运要比攻击强，必须要有一定量的积累。**
首先，少量的幸运与高攻击有一样的好处，就是清理残兵，对于消灭一个单位至少需要两次攻击，10级攻击(需要100点)可以提供同级小兵对垒4%-5%的攻击加成，两次稳定造成8%~10%伤害（高防地形，对于攻击加成就趋于不明显），而由于现在运算公式，+5%运气可以直接造成平均5%的伤害，这对与清理1hp小兵来说是十分关键的。
幸运重要的一点，就是直接提升了多一次攻击的价值，攻击加成大多数是在同级中奏效——高等级打低等级，无论多少都能打残并且有较少的反伤，反观幸运，无论何种情况都能给你带来优势，(这是由于现在的简化公式造成的)，如此看来，即使是1级的幸运，都可以直接改变你出兵的策略(有时候2hp坦克摸不死，+5%就有可能摸死)，在现在伤害表变化不明显的DOR，幸运的价值就更大了。
因此，**无论是高运气还是低运气，都优于相近花费的攻击加成。**这在未来梯度变大的时候也许会更明显。
我认为这是简化公式所造成的，而不是系统平衡的原因

**Comment by Babygogogo** [comment]
谢谢赵天同！我补充少许内容作为背景知识：
1. 目前游戏中的幸运伤害计算只跟进攻方的HP、幸运上下限有关，跟其他一切因素无关。举个例子，如果某玩家的幸运上下限是60%/10%，他的一个9HP部队发起进攻，那么平均造成的幸运伤害是(60+10)/2*0.9=31.5%
2. 原版老三代中，幸运伤害与防御方的加成、地形等有关，具体公式是：
   基础值x（攻击方HP/10）x[200-（防守方防御能力+地形防御星数x防守方HP）]/100  
3. 游戏默认的幸运上下限是10%/0%

**Comment by 3Au** [comment]
1.首先我十分同意FTK的观点；
2.幸运是个很神奇的东西，作为不确定因素增加了游戏多变性。但是在AWBW中，不管强度如何幸运三人组在联赛中一直是被关小黑屋的。原因很简单，不确定因素对这几个CO来说不可控。很容易把战略游戏玩成猜拳游戏。至于Rachel没有关黑屋主要在于她的是特技加幸运，而且相对来说加的不多，仍然是可控的。
3.所以我会得出这么个结论，对日常幸运要达到可控的地步。如何可控，诚然去限制幸运技能是不可取的，玩法和组合就这么一刀砍怎么想也不合理。为此除去幸运技能，对可控性的把握落在了非幸运CO(对babywar来说就是没加幸运技能状态)的幸运调控上。
4.原作的幸运伤害可以用如下函数表示：
实际幸运伤害=f(随机出的幸运值,自己HP,敌人各项防御加成)
其中随机出的幸运值是一个初始值，也就是最直观的幸运上下限表述，非特殊情况下为0-10。需要注意的是，敌人防御加成中有地形加成这一项，这一项会受到敌人hp影响
5.可以看出原作设定下，幸运不过是一种基础攻击微弱增幅。意义也在于提供随机性。但对于重要情况，比如老三代的3防地形的防守地位几乎不可感动。真因为如此成就了aw可以以少打多的局面。不确定因素加上可控的设定，这也是体现游戏战术战略性的一个方面。
6.目前系统下幸运不受防御影响(受hp影响鄙人暂不清楚)，上述3星防御地位直接被破。当然dor系统下3星地形本来也会有五分之一概率破但是这个概率还是小，直接限制了玩家在无攻击加成下强攻3星地形。如果幸运不受防御加成影响，3星地形被破概率大幅度增加。仅此一点，就让游戏大量偏向于局部兵力和部队配比的比拼，战术布阵等比重下降。而以上只是一个方面，残血补刀，对残血补刀，以及从高伤一击跨越到秒杀一击这些影响更不必多说。
7.最后是关于幸运数直接加还是按照比例增加的问题。以公路对A为例，55算满幸运是65，按比例则只有最多60.5取整数60，这个影响非常大了，直接封印残血和低攻补刀，而高伤更容易跨过界限变为秒杀。aw的精髓就是大部分情况至少2击破，1击破可以提供缺口导致直接一步毁灭敌方阵型，又会变为上述的兵力和构成的比拼比重加强，游戏性改变。
7.不过现在还有个问题，跟主题关系不大。就是dor系统下1.1攻超大概率破3星防。。。这在awbw时代是难以想象的，而且。。1.1攻对于原作半数以上无日常大范围加攻CO来说，一座塔就解决了。直接导致1.2攻地位动摇。也不知道是不是好事

**Comment by Babygogogo** [comment]
目前，防御方的防御加成（包括技能，地形等），会按比例抵消掉幸运伤害。举例而言，如果进攻方是6HP，且幸运上限是70，而防御方的防御加成为40%（比如步兵站在山上，玩家无技能加成），那么实际造成的幸运伤害的上限是0.6*70/(100%+40%)=30%。
如无意外，这个公式将不会再行修改，但由于幸运实际效果被削弱（以前无视防御，现在会被抵消），所以技能点消耗是否需要调整将成为另一个课题。

顺带一提，根据上述公式，负防御加成将使得受到的幸运伤害增加。

本issue的目的目测已经达到，故暂且关闭。
