### ISSUE TITLE
新技能设计

### ISSUE THREAD

**Issue by LlMT13496** [Babygogogo/BabyWars#51]
主动类技能，机械类兵种攻击力按己方所有的建筑物数量×10％来计算，技能点等级只有一级，技能点大约1000左右，在大地图的技能，虽然强但是弱点也很明显，怕兔子

**Comment by Babygogogo** [comment]
谢谢提议！不过目前游戏优先实现原版已有的技能，所以新型技能可能要延缓实现了，还望理解：）
