### ISSUE TITLE
日常幸运技能bug

### ISSUE THREAD

**Issue by zhaotiantong** [Babygogogo/BabyWars#55]
对方发动power后，我的所有幸运失效

**Comment by blackwave** [comment]
关于此bug的具体描述：
玩家A 日常-100%攻 + 90%幸运上限
玩家B 日常-10防
日常情况下玩家A可以对B造成跟幸运有关的伤害

玩家B发动COP后，部队增加10防，之后玩家A不能再对玩家B造成任何伤害

**Comment by Babygogogo** [comment]
bug已判明，这实际上与防御无关，只与进攻方的攻击力加成有关。谢谢反馈！
