### ISSUE TITLE
关于幸运伤害过强的问题

### ISSUE THREAD

**Issue by HappyAlfred** [Babygogogo/BabyWars#56]
我觉得，可以让幸运伤害不能致死
比如，自己的tank有60hp，对方tank对己方tank只有55伤害。那么即使幸运爆发，最多也只能打成1hp而不能致死，除非补一刀
这样也可以避免没有干掉某些拼运气才能干掉的单位而乱了阵脚

**Comment by 3Au** [comment]
那拿幸运补刀1-2血的单位补不死更蛋疼。
别老想着改系统啊，从其他主观因素入手

**Comment by RushFTK** [comment]
今天幸运伤害已经根据需要进行了修改 #61 因此该问题结束讨论(先看新的运气系统执行情况)。
