### ISSUE TITLE
关于一项能力的上/下限

### ISSUE THREAD

**Issue by blackwave** [Babygogogo/BabyWars#57]
建议设定每项技能的上/下限，从而防止日常能力与技能叠加后超越上下限带来的不良影响。另外杜绝-4射程-200%攻击。

**Comment by Babygogogo** [comment]
附议黑波，这个课题涉及的技能很多，我觉得可以考虑先从攻击下限开始着手。我建议削弱攻击下限，理由如下：
- 过低的攻击显得很极端（原作及awbw中，全体减攻的下限为-20%）
- 日常攻-100%再配合主动技攻-100%，实际上等于-100%攻，也就是说主动技的-100%没有负面影响，反而赠送了技能点

个人建议，可以考虑把下限调整为-50%。

**Comment by blackwave** [comment]
。。我觉得无所谓。只要不出负数攻击就好了。。过低的攻击想必也不会有人用。。

**Comment by RushFTK** [comment]
我认为保持现有的上下限有现有的好处。
（1）  **这突出了BabyWars**（以下简称本作）**的特色**。本作的重要特色之一就是高度的自由性，虽然极端数值会有很多不是单纯数值累加上效果的不同(比如145攻可以直接秒杀小兵从而破阵)，而使得话费的点数数值还需要值得商榷，不过如果减小了上下限，一定程度上减小了该游戏自由创造的特征。

（2）  **越界数值可以从其他方式获得惩罚**。如同@blackwave 所说的：

> •日常攻-100%再配合主动技攻-100%，实际上等于-100%攻，也就是说主动技的-100%没有负面影响，反而赠送了技能点

可以通过设定负攻击使你的对手回复生命值，来让玩家考虑如何搭配到-100%攻，因为有些人可能设置的技能就是日常0攻，而有些人只需要在COP时候0攻，现在减小上下线等于抹杀了这些搭配方法。

（3）  **现在游戏仍处于测试阶段，范围大的情况下获得尽可能多的数据，对将来平衡具有好处。**出于竞技考虑的维护可以等到游戏系统稳定，地图完善的时候再适时定做， 如果现在开始抹杀，未来也比较难以获得测试数据从而再度开放。

**Comment by Babygogogo** [comment]
关于RushFTK说的三点，我提一下个人意见：
1. 自由度确实是BabyWars的主要特色，但作为战略游戏，至少在竞技模式下，平衡性是首要的考虑因素。
2. 负攻击给攻击对象回血可能不是个好主意，最主要的原因是让游戏进一步复杂了，次要的原因是这略显扯淡……步兵交火，子弹扫过去，对方毫发无损，还多出个人来了……
3. 这一点我也考虑过，而且同意你的说法。但现实问题在于，技能多了，导致负责调整的人的工作量巨幅增加。而你我都知道，BabyWars不会为参与者支付工资，我们不可能强制要求哪位同志付出什么劳动。

基于上述原因，我还是认为削减上下限是目前比较可行的方法。

**Comment by RushFTK** [comment]
> 1.自由度确实是BabyWars的主要特色，但作为战略游戏，至少在竞技模式下，平衡性是首要的考虑因素。

我并不认为单单限制上/下限就算是平衡性了。 150攻基本能完全破阵；但是-50的防也可以让你被完全破阵，因为自己带着debuff才有着强力的技能，这是一种权衡，150与200区别已经基本不大了，不过他的区别也是玩家考虑的要素。如果经过仔细斟酌，就应该得出就算我带200也没有意义(或者有我们想不到的特殊情况会有作用)。也就是说，很高的上下线不是摆设，是有着让玩家诱导去尝试的可能，这样适度选技能就是一门策略，一门学问；我不想在不改变代码体积的情况下让他变得浅薄。

> 2.负攻击给攻击对象回血可能不是个好主意，最主要的原因是让游戏进一步复杂了，次要的原因是这略显扯淡……步兵交火，子弹扫过去，对方毫发无损，还多出个人来了……

这游戏"不合理“的因素太多啦，而且这种惩罚只是让玩家不要配出-100%以上的攻击力。

**Comment by Babygogogo** [comment]
其实说白了，最现实的原因就在于，没有人专职调整平衡。如果有的话，那么的确可以把上下限定的很高，让专职的人慢慢调整，但现在我们并没有这种条件。即便是使用issue让大家一起讨论，过高的上下限也会成为大家思考的障碍。所以，我就只能把上下限降低来减少调整所消耗的时间了。

顺便再说一下，我并没有永久禁用这些极端的上下限，在未来的娱乐模式中我会开放它们。如果能得到妥善的平衡，它们也会被加入到竞技模式。

**Comment by Babygogogo** [comment]
由于本issue涉及面较广，而且已长时间没有人回复，所以暂且关闭。关于技能上下限，建议以后对每一个有需要调整的技能单独开一个issue，方便查看跟踪。
