### ISSUE TITLE
关于减射程的建议

### ISSUE THREAD

**Issue by blackwave** [Babygogogo/BabyWars#58]
推荐把减射程的下限改成-1.因为-2实在是和-1差不多。而且-1最好最为这一条线的下限。（顺便杜绝大家蹭技能点）

**Comment by RushFTK** [comment]
由于增加了反坦克炮这种近战远程系均可用的单位，其实-2和-1应该稍有区别的。即使是-1，反坦克炮依然有可以出做肉盾的价值。而-2则完全消灭了远程。不过可以调整-1和-2奖励的点数差距。

**Comment by Babygogogo** [comment]
从简化技能上下限的角度考虑，我比较赞同移除-2射程。不过由于目前代码功能不足，暂不能禁止叠加负面影响，请见谅。

**Comment by blackwave** [comment]
@RushFTK 不懂射程跟反击（肉盾）有啥关系

**Comment by 3Au** [comment]
表达一下观点
1、禁止负面效果叠加我表示赞同
2、移除-2射程我也赞同

**Comment by RushFTK** [comment]
@blackwave 我意思是我仍然可以拿反坦克当作步兵后面的一层肉盾，-2就完全是累赘了233.

**Comment by RushFTK** [comment]
现在减少射程的方案已经实施（ #65 ）因此关闭问题，在日后如有更多建议会重新开放问题
