### ISSUE TITLE
日常上下限

### ISSUE THREAD

**Issue by HappyAlfred** [Babygogogo/BabyWars#62]
日常攻防-30~+30
因为awbw里也从未出过超出这个数值的，dor的co以后再说
日常移动-1~+1
+1移动需要300~400已经可以了我觉得，代价是巨大的，-1移动本身作为一个巨大的代价，也是300~400
日常幸运最大值-10~+20，参照jugger，我不希望出现0攻100幸运这样的奇葩
日常幸运最小值-10~+10，也是参照jugger
日常造价-20~+20，为了方便计算，公式改成原价*（1+改变值）就好了，cop造价直接改变日常造价。cop的造价如果大于d2d造价，需要技能点，反之是反馈技能点。
日常占领+0~+50，参照sami
日常收入-10~+10，参照sasha

**Comment by RushFTK** [comment]
建议该项目与 #57 合并在一起讨论，另外关于造价问题也参见 #59 的表格。

**Comment by RushFTK** [comment]
技能上下限已经在 #57 详细讨论，因主题重复，故关闭。
