### ISSUE TITLE
关于造价1667，手上却只有1666的问题

### ISSUE THREAD

**Issue by HappyAlfred** [Babygogogo/BabyWars#63]
我建议是资金和造价相差10时，比如1663，1670时，可以把资金变成0购买那个单位，虽然不是长久之计，但是可以解燃眉之急

**Comment by Babygogogo** [comment]
感谢阿飞，这个提议值得考虑。从计算精度问题来考虑，目测可能相差1可以这么做，2以上就应该禁止购买。

**Comment by zhaotiantong** [comment]
如果真的想修复，还有一个改法，就是把四舍五入制改成小数全舍，这样自行车日常1666，随时多剩几块钱也没关系

**Comment by zhaotiantong** [comment]
或者就不改了，让大家感受一下33%的恶意也不错_^_^_

**Comment by Babygogogo** [comment]
是的，小数全舍去还更简便。从偷懒的角度考虑，我还是舍去小数吧。

P.S. 我感觉这更像是某个曾经被1666坑过的同学的恶意……

**Comment by RushFTK** [comment]
考虑到增加收入与减小造价的等效性。我认为不应该这样修正。
1666价格有时放在增加收入中可能就是差100买不到的情况。

**Comment by Babygogogo** [comment]
@RushFTK 并非如此，以1666为例子来说明吧。假设玩家的造价是正常的66.67%（注意，这个数字实际上是2/3，66.67%是近似值），那么一个摩托兵（原价2500）的造价取整后就变为了1667。如果玩家手上持有5000金钱，那么他只能买2个，之后剩下1666，无法购买第三个。
但如果从公式考虑，那么摩托兵真正的造价是2500/3*2，实际上5000块钱刚好能买3个，不多不少。由于计算时需要取整，使得造价变成了1667，才造成了差1块钱无法购买第三个。
总而言之，这并不是差100这么严重的问题，而仅仅是计算精度的误差而已。因此，阿飞和赵天同的思路都是有道理的，其中赵天同的解决方法更精确（且简单），所以我采用了。

如无人反对，这条issue已经算是解决了。
