### ISSUE TITLE
dor或老三代的完整伤害公式是？

### ISSUE THREAD

**Issue by Babygogogo** [Babygogogo/BabyWars#68]
如题，原作的伤害是和**被攻击对象**的HP有关的，但具体公式我并没有找到。这也导致目前游戏的伤害公式是无视被攻击对象的HP的。如果有同志知道，烦请发一下，我好进行修正，谢谢！

**Comment by MtDesert** [comment]
假设步兵间损伤是55%，那么10HP的情况下，damage就是55%，9HP就是55%×9/10=49.5%，8HP就是55%×8/10=44%以此类推

**Comment by Babygogogo** [comment]
在网上找到的一个公式：
D%=[B*ACO/100+R]*(AHP/10)*[(200-(DCO+DTR*DHP))/100]
D = Actual damage expressed as a percentage
B = Base damage (in damage chart)
ACO = Attacking CO attack value (example:130 for Kanbei)
R = Random number 0-9
AHP = HP of attacker
DCO = Defending CO defense value (example:80 for Grimm)
DTR = Defending Terrain Stars (IE plain = 1, wood = 2)
DHP = HP of defender

**Comment by blackwave** [comment]
攻击伤害= 攻击方HP数/10_(基础伤害_（1+攻击加成）+luck)_(1-防御加成-地形加成_防御方HP数/10）

**Comment by Babygogogo** [comment]
感谢黑波，经过修正和重构后，现在游戏的伤害值和DoR原版的已经基本没有差别（不过不排除我测试不完整的可能性）。如无意外，本周末会实装本次修正。
