### ISSUE TITLE
回合状态引发错误

### ISSUE THREAD

**Issue by Babygogogo** [Babygogogo/BabyWars#69]
![qq 20160907194659](https://cloud.githubusercontent.com/assets/8947358/18310994/6659ac0c-7534-11e6-9335-f2962a020d14.png)
![qq 20160907194921](https://cloud.githubusercontent.com/assets/8947358/18310997/6abd7c60-7534-11e6-809d-32f41df23fda.jpg)
如图，是对方回合时出现错误。图片上显示的错误信息似乎显示了ModelPlayerManager的doActionProduceOnTile函数出错，具体原因未知。

**Comment by RushFTK** [comment]
> 金钱计算错误

弱弱的问一下，何以判断的(

**Comment by Babygogogo** [comment]
第一幅图第一行右方出现了setFund字样，说明这个函数出错了。这个函数是用来设置玩家持有的金钱的，我给它加了断言，如果参数不是非负整数就报错。然后我又仔细看了底层的字，大概看到了doActionProduceOnTile字样，说明是它引起的错误。不过具体是如何引起的，暂时无法知道了。

**Comment by Babygogogo** [comment]
现判明这个bug是由于网络状况不良，导致的客户端与服务端不同步而引发的。经过前一段时间的更新，类似的bug已经较少出现，故暂时关闭本issue。
