### ISSUE TITLE
关于rig，燃料和补给线

### ISSUE THREAD

**Issue by HappyAlfred** [Babygogogo/BabyWars#78]
老三代的单位燃料都非常多，以至于APC几乎没有用处
dor的单位燃料虽然相对来说少了点，但是还是没有影响到rig的出场，除了飞机和潜艇可能会需要rig
我的想法是……
每个单位的燃料很快就会耗尽，需要用rig来提供补给线
比如，tank的燃料只有20，燃料限制了它的移动，需要及时的补给才能让它发挥出效果
空军的燃料比起陆军要多一些，但是还不够，只有40燃料，需要临时空港的补充
海军燃料是较多的，有60点
步兵的燃料是“口粮”，移动不会消耗，但是每过一天就会消耗1点。步兵只有5天的口粮，口粮耗尽时每回合-3HP。这让步兵系更依赖城市和rig
tc可以空投物资以补给附近的单位，也可以修复附近的步兵

**Comment by Babygogogo** [comment]
目前游戏功能尚不完善，为避免造成老玩家的不适应，关于兵种和地形都将尽量以DoR原作为标准来设定。相关修改需等到游戏功能基本完成后再行讨论和实行，因此本issue暂时搁置，还望理解：）
