### ISSUE TITLE
主动技能的最小星数是否有必要

### ISSUE THREAD

**Issue by Babygogogo** [Babygogogo/BabyWars#80]
技能系统刚诞生的时候，是没有主动技能最小星数这个概念的。也就是说，只要玩家愿意给自己加上足够多的负面影响，就可以用很短的气槽实现极为强大的效果。
一星刷五血就是这个时期的产物之一。很明显，这样的技能极为可怕。为了封堵这种配置，最小星数的概念诞生了，它对每个主动技所需要的最小星数都做了限定，这就使得短气槽能够选择的技能少了很多（目前刷五血最低要求十五星）。
而随着时间和实践的推进，许多负面技能在目前都已经被取消（比如著名的玄武流），而且赠送的技能点数也都大幅削弱（比如攻击力，最初-50%攻击能够获得500技能点，而现在最多只能-30%攻击，且只能获得75点技能点）。即使给自己堆满负面技能，能够获得的点数也已经不多了（截止目前，如果使用三个负面技能，最多也只能赠送140点，而且会大幅削弱我方战力）。也就是说，想要用短气槽发动强力技能，即使没有最小星数的限制，也已经不是一件很容易办到的事情了。当然，某些技能的点数需求过低是个问题（这导致了配置出来的co能力很容易就达到了原版游戏的top水平以上），但这与本issue的主题没有直接关系，日后会另开issue处理。
综上，最小星数是否依然必要，在我看来可能需要打个问号了。

另外，这并不会马上实装，如果大家都反对我就会放弃。欢迎讨论：）

**Comment by blackwave** [comment]
当然有了。。这个设定很好啊

**Comment by Babygogogo** [comment]
黑波能否举一个具体点的例子说明一下？比如说，取消了XX技能的最小星数限制会导致什么后果，而且即使提高其技能点消耗也无济于事的？

**Comment by blackwave** [comment]
这个倒是一时想不起来。。但是还是有很多技能技能点比最小要低的。而且我觉得这设定很科学（比如再动，如果你不设最小说不定6星就再动了）

**Comment by Babygogogo** [comment]
刚好我也在回复关于再动的issue，目前来看，再动被削应该只是时间问题了。假设再动需要消耗900点，再考虑上面说的负面技能最多只能赠送140点，那么还是最少需要8星（而且此时技能强度相当低）。如果进一步牺牲日常属性，那么再动最少可以7星发动，但此时的技能强度会更低。

**Comment by blackwave** [comment]
再动现在并不强势。现在是强D2D时代而且多金钱流。建议观望再动。。而且最小星数要保留

**Comment by Babygogogo** [comment]
是的，目前的日常金钱+攻防明显是过于op了，这周的更新肯定会削，只是还没有确定是直接禁用或者是提价。

**Comment by zhaotiantong** [comment]
如果把星数取消，将能配出1星减5/7油这种丧心病狂的特技。而现在减油根本没人用，并不是因为减油强才丧心病狂

**Comment by zhaotiantong** [comment]
如果把星数取消，将能配出1星减5/7油这种丧心病狂的特技。而现在减油根本没人用，并不是因为减油强才丧心病狂

**Comment by Babygogogo** [comment]
鉴于无人支持取消最小星限制，本issue关闭。
