### ISSUE TITLE
变体伤害除法公式推荐

### ISSUE THREAD

**Issue by 3Au** [Babygogogo/BabyWars#90]
目前babywars采用的是有综合的除法公式，其中最主要的部分是（1+攻击系数）除以（1+防御系数）来计算伤害。
本公式的特点是当攻防系数相差不变，攻防系数本身越高，防御价值越低。这也是原理上攻防等价实际上攻击要比防御值钱的原因。这里推荐一个变体公式：
![image](https://cloud.githubusercontent.com/assets/21301185/18950266/a8518460-8671-11e6-9deb-b5aabdc0d965.png)
其中C为基础伤害，A为攻击系数，D为防御系数（包含了自身和地形防御系数），ABS为绝对值，SIGN为返回正负值。
其实这个公式意思就是，当攻击和防御都有加成或降低时，让攻击和防御相互抵消，未抵消部分再用来计算。举个例子，比如攻击方1.1攻，防御方1.3防，则抵消0.1，当做攻击方1.0攻，防御方1.2防来进行除法公式计算。
这个公式大体上实现了真正的攻防等价。也不会破坏dor原有的计算系统

**Comment by Babygogogo** [comment]
首先补充一点背景知识：
- 如果防御方总防御值大于100，那么用除法来计算伤害值。举例，如果我方某部队的总防御值是130（比如玩家自带-10防御加成的步兵站在山上），那么敌人对这个部队造成的伤害是原来的100%/130%=76.92%，与DoR原版一致。
- 如果防御方总防御值小于100，那么是用_乘法_来计算伤害值。举例，如果我方某部队的总防御值是70，那么敌人对这个部队造成的伤害是原来的100%*(100%-70%+100%)=130%（由于DoR原版似乎没有负防御公式可参考，而且我希望使得负防御使得伤害值线性增长，所以用了乘法）。

为了更直观，补充一点当前公式和这个变体公式的比较（均以%为单位）：

| 总攻击 | 总防御 | 当前伤害 | 变体伤害 |
| --- | --- | --- | --- |
| 160 | 120 | 133.33 | 140 |
| 140 | 120 | 116.67 | 120 |
| 120 | 120 | 100 | 100 |
| 100 | 120 | 83.33 | 83.33 |
| 80 | 120 | 66.67 | 71.43 |
| 60 | 120 | 50 | 62.5 |
| 160 | 80 | 192 | 180 |
| 140 | 80 | 168 | 160 |
| 120 | 80 | 144 | 140 |
| 100 | 80 | 120 | 120 |
| 80 | 80 | 96 | 100 |
| 60 | 80 | 72 | 83.33 |

可以看到在防御较高时，在大多数情况下变体公式算出的伤害值比原先更大，也就是防御进一步贬值了；在防御较低时，如果攻击力高则伤害值比原先的小，攻击力低时伤害值比原先的大。总体来说这是个很微妙的公式……

**Comment by Babygogogo** [comment]
换了个思路再思考，公式确实实现了攻防大体等价，但由于高防御时采用的除法公式，相应的低攻击时也变成了除法公式。举例而言，一般我们期望50%攻击力时，对敌方造成的伤害就是原来的50%，但在变体公式下，造成的伤害却达到了66.66%，而且账面攻击力越低，实际攻击力相对越高（就类似账面防御力越高，实际效果越不明显）。这么看来这个公式似乎就不可用了……

**Comment by 3Au** [comment]
我似乎只考虑了相对伤害变化。其实之前计算只取了防御系数大于攻击系数的情况，发现这种情况下防御不利。看了这个表才发现变体公式果然还是有问题

**Comment by zhaotiantong** [comment]
现先的公式
伤＝HP（基（1+塔+攻）+幸）/（1+防+地）
偏伤/偏攻＝HP基/（1+防+地）
偏伤/偏防＝-HP（基（1+塔+攻）+幸）/（1+防+地）^2
令-偏伤/偏防＞偏伤/偏攻
则基＜幸/（防+地-攻-塔）
也就是说满足这个式子，双方同时加等量的攻防，加防就强，否则加攻强
一般，幸＝5
同单位内战，基＝55
则防+地-攻-塔＜9.1%时加防御合算
由地＝星*HP%，一般认为在10%左右
所以一般认为在攻防相同时，无塔图加攻强，一塔图差不多，二塔图加防强……攻防不同时，攻防基本上越接近越强
